#! /bin/sh
# vim:foldlevel=0
# vim:foldmethod=marker

. ~/.config/bspwm/bspwm_theme

bspc config split_ratio                 0.54
bspc config borderless_monocle          false
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config pointer_follows_focus       false
bspc config auto_cancel                 true
bspc config ignore_emwh_focus           true
bspc config border_width                6
bspc config window_gap                  20
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true
bspc config top_padding                 14

bspc rule -a '*:*' state=floating

bspc subscribe monitor | while read -r line; do
case $line in
    monitor_add*|monitor_geometry*)
        ~/.config/bspwm/scripts/configure_monitors "$(bspc query -M | wc -l)"
        ;;
    *)
        ;;
esac
done &

xrandrconf
$HOME/.config/polybar/launch.sh
