#! /bin/sh
# vim:foldlevel=0
# vim:foldmethod=marker

# Colors {{{1

#fetch colors from current X theme
colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\*color)([0-9]):/\10\2:/g;' /dev/shm/current-theme | grep 'color[01][0-9]:' | sort | sed 's/^.*: *//g' ) )

bspc config presel_border_color "#B0FFF2"
bspc config focused_border_color ${colors[13]}
bspc config normal_border_color "#000000"
bspc config active_border_color "#555753"
bspc config urgent_border_color "#4e9a06"

# Settings {{{1
bspc config split_ratio                 0.54
bspc config borderless_monocle          false
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_follows_monitor     true
bspc config pointer_follows_focus       false
bspc config auto_cancel                 true
bspc config ignore_emwh_focus           true
bspc config border_width                1
bspc config window_gap                  48
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true


# Destktops/ Workspaces {{{1

#external script to configure monitors and desktops
monitor_configure

# Window rules: {{{1
bspc subscribe | awk -F ':' '$3 ~ /^[FO]/ { exit(system("qutebrowser &")); }' &
bspc rule -a skype desktop='^9'
bspc rule -a Pim state=floating
bspc rule -a mpv state=floating
bspc rule -a libreoffice-calc state=floating
bspc rule -a Zathura state=floating
bspc rule -a gtk-gnash state=floating

# Start bspc: {{{1
killall -9 panel panel_bar

panel &
# bspc desktop -f ^1
