#!/bin/bash

if [ "$1" -eq "3" ]; then
    bspc monitor $(bspc query -M | sed -n 1p) -d 0 3 6
    bspc monitor $(bspc query -M | sed -n 2p) -d 1 4 7
    bspc monitor $(bspc query -M | sed -n 3p) -d 2 5 8
elif [ "$1" -eq "2" ]; then
    bspc monitor $(bspc query -M | sed -n 1p) -d 0 2 4 6 8
    bspc monitor $(bspc query -M | sed -n 2p) -d 1 3 5 7 9
else
    bspc monitor -d 0 1 2 3 4 5 6 7 8 9
fi
$HOME/.config/polybar/launch.sh
