#!/bin/bash

mouse_move_direction() {
    if [[ $1 == "empty" ]]; then
        length=8
    elif [[ $1 == "shift" ]]; then
        length=48
    else
        length=308
    fi
    case $2 in
        left)
            echo "-- -$length 0"
            ;;
        down)
            echo "0 $length"
            ;;
        up)
            echo "-- 0 -$length"
            ;;
        right)
            echo "$length 0"
            ;;
    esac
}

if [[ -f /dev/shm/jmode ]]; then
    JMODE=`cat /dev/shm/jmode`;
else
    JMODE="JOY";
fi;

if [[ $JMODE == "JOY" ]]; then
    if [[ $1 == "empty" ]]; then
        extra="f"
    else
        extra="s"
    fi

    bspc window -$extra $2
elif [[ $JMODE == "MOUSE" ]]; then
    mouse_side=`mouse_move_direction $1 $2`
    xdotool mousemove_relative $mouse_side
fi
