#!/bin/sh

source ~/bin/panel_colors

NOTIFY_HEIGHT=14
len=`echo $@ | wc -c`
NOTIFY_WIDTH=$(($len*6 + 6))
NOTIFY_GEOMETRY="${NOTIFY_WIDTH}x${NOTIFY_HEIGHT}+0+0"
LINEHEIGHT=3

play -q ~/Sounds/stereo/bell.ogg &

(echo " $@"; sleep 5)\
| bar \
        -B "$COLOR_BACKGROUND" \
        -F "$COLOR_FOREGROUND" \
        -g "$NOTIFY_GEOMETRY"\
        -u $LINEHEIGHT\
        -b &
