#!/bin/bash

CPT_B=0
CPT_S=8
count=0
bold=0
while read HEXCODE; do
    if [ $count -eq 19 ]; then
        echo *background: [90]$HEXCODE
    elif [ $count -le 15 ]; then
        if [ $count -eq 1 ]; then
            echo *foreground: $HEXCODE
        fi
        if [ $bold -eq 0 ]; then
            printf '*color%d: %s\n' "$CPT_B" "$HEXCODE"
            let CPT_B++
            bold=1
        else
            printf '*color%d: %s\n' "$CPT_S" "$HEXCODE"
            let CPT_S++
            bold=0
        fi
    fi
    let count++
done | column -t
